---
title: "Data Viz - Final Project (Group J)"
author: "Katherine Lin, Juna Kawai-Yue, Humaira Ahmed"
date: "2025-04-18"
output: html_document
---
### Let's do some data input & merge
```{r}
# Health code violations
hcv <- read.csv("~/Desktop/Data_Viz/hcvyear.csv")

# Merging
```
```{r}
library(dplyr)
nyczips <- read.csv("~/Desktop/website/data/nyc-zip-codes.csv")
dta <- read.csv("~/Desktop/Data_Viz/22zpallagi.csv")
  
dta_nyc <- dta[dta$zipcode %in% nyczips$ZipCode, ]
  
  income_filtered <- dta_nyc %>%
    select(STATE, zipcode, agi_stub, A00100, A02650)
  
  # average AGI and income per ZIP code
  avg_income <- dta_nyc %>%
    group_by(zipcode) %>%
    summarise(
      avg_AGI = mean(A00100, na.rm = TRUE),
      avg_income = mean(A02650, na.rm = TRUE)
    )

write.csv(avg_income,"~/Desktop/website/avg_income.csv", row.names = FALSE)
```
```{r}
library(dplyr)
cleaned_hcv <- hcv[c("dba", "boro", "building", "street", "zipcode", "cuisine.description", "inspection.date", "violation.code", "violation.description", "critical.flag", "latitude", "longitude")]
count_whole <- function(data){
  data %>%
    filter(inspection.date != 1900-01-01)  %>%
    filter(critical.flag != 'Not Applicable')
}

clean_hcv_2 <- count_whole(cleaned_hcv)
write.csv(clean_hcv_2,"~/Desktop/website/hcv.csv", row.names = FALSE)

```

```{r}
library(data.table)

dt <- fread("~/Desktop/website/data/hcv.csv")
saveRDS(dt, "~/Desktop/website/data/hcv.rds")
```
### Now let's extract the counts per restaurant listed
```{r}
library(dplyr)
# Let's first make a function
count_bor <- function(data, target){
  data %>%
    filter(boro==target) %>%
    filter(critical.flag != 'Not Applicable') %>%
    filter(inspection.date != 1900-01-01) %>%
    count(dba, building, street, zipcode, cuisine.description, latitude, longitude, address, name = 'hcv_count')
}

#apply to whole data set such that each line is a restaurant (rather than multiple entries)
count_whole <- function(data){
  data %>%
    filter(inspection.date != 1900-01-01)  %>%
    filter(critical.flag != 'Not Applicable') %>%
    count(dba, building, street, zipcode, cuisine.description, latitude, longitude, address, name = 'hcv_count')
}

hcv$address <- paste(hcv$building, hcv$street, hcv$zipcode)
# Let's create a new data frame to do so
hcv_man <- count_bor(hcv, 'Manhattan')
hcv_bronx <- count_bor(hcv, 'Bronx')
hcv_brook <- count_bor(hcv, 'Brooklyn')
hcv_queen <- count_bor(hcv, 'Queens')
hcv_stat <- count_bor(hcv, 'Staten Island')
hcv_total <- count_whole(hcv)

# Now let's sort & take top 10
top10_man <- hcv_man %>%
  arrange(desc(hcv_count)) %>%
  slice(1:10)

top10_bronx <- hcv_bronx %>%
  arrange(desc(hcv_count)) %>%
  slice(1:10)

top10_brook <- hcv_brook %>%
  arrange(desc(hcv_count)) %>%
  slice(1:10)

top10_queen <- hcv_queen %>%
  arrange(desc(hcv_count)) %>%
  slice(1:10)

top10_stat <- hcv_stat %>%
  arrange(desc(hcv_count)) %>%
  slice(1:10)
```
### Let's pull reviews from some places in Brooklyn (Example code)
```{r}
library(googleway)

# master wok, arch diner are closed (top 1 and 2)
# let's run this on the other 8 though
# First let's just pull out the dba and latitude and longitude into single dataframe & remove first two rows
top10_brook_loc <- tail(top10_brook[c('dba', 'latitude', 'longitude')], 8)
```
```{r}
key <- 'key'

get_reviews <- function(df, key){
  latitude <- as.numeric(df$latitude)
  longitude <- as.numeric(df$longitude)
  
  results <- google_places(search_string = df$dba, 
                           location = c(latitude, longitude),
                           key = key) # search up location and grab information it
  
  details <- google_place_details(place_id = results$results[1, "place_id"],
                                   key = key) # grab more details based on the place_id generated prior
  
  reviews <- data.frame(details$result$reviews) # pull out 5 reviews per location
  
  if(nrow(reviews) != 0){ 
    reviews$restaurant <- df$dba # add in restaurant name if reviews are present
    reviews$rating <- details$result$rating # Add column for main average rating of the restaurant (not ratings provided by the reviewers)
  }
  
  return(reviews)
}

brook_revs <- bind_rows(apply(top10_brook_loc, 1, function(row){ # run function on data frame of top 10(ish)
  row <- as.list(row) # run it on the rows individually (we need to convert this to list to work)
  reviews <- get_reviews(row, key) # run function with personal key
  
  return(reviews)
}))

write.csv(brook_revs,"~/Desktop/website/data/brook_revs.csv", row.names = FALSE)

# Unable to get reviews for Grace Caribbean Cuisine -> total of 35 reviews & ratings
```
### Let's categorize the violation codes & descriptions
```{r}
# Pull unique violation codes & descriptions & save to a file
filtered_data <- hcv %>%
  distinct(violation.code, violation.description)

write.csv(filtered_data,"~/Desktop/violations.csv", row.names = FALSE)
```







