---
title: "Data Viz - Final Project (Group J)"
author: "Katherine Lin, Juna Kawai-Yue, Humaira Ahmed"
date: "2025-04-18"
output: html_document
---
### Let's do some data input & merge
```{r}
# Health code violations
file_path <- "~/Desktop/Data_Viz/hcvyear.csv"
hcv <- read.csv(file_path)

# Income


# Merging
```
### Now let's extract the counts per restaurant listed
```{r}
library(dplyr)
# Let's first make a function
count_bor <- function(data, target){
  data %>%
    filter(boro==target) %>%
    filter(critical.flag != 'Not Applicable') %>%
    filter(inspection.date != 1900-01-01) %>%
    count(dba, building, street, zipcode, cuisine.description, latitude, longitude, name = 'hcv_count')
}

#apply to whole data set such that each line is a restaurant (rather than multiple entries)
count_whole <- function(data){
  data %>%
    filter(inspection.date != 1900-01-01)  %>%
    filter(critical.flag != 'Not Applicable') %>%
    count(dba, building, street, zipcode, cuisine.description, latitude, longitude, name = 'hcv_count')
}
# Let's create a new data frame to do so
hcv_man <- count_bor(hcv, 'Manhattan')
hcv_bronx <- count_bor(hcv, 'Bronx')
hcv_brook <- count_bor(hcv, 'Brooklyn')
hcv_queen <- count_bor(hcv, 'Queens')
hcv_stat <- count_bor(hcv, 'Staten Island')
hcv_total <- count_whole(hcv)

# Now let's sort & take top 10
top10_man <- hcv_man %>%
  arrange(desc(hcv_count)) %>%
  slice(1:10)

top10_bronx <- hcv_bronx %>%
  arrange(desc(hcv_count)) %>%
  slice(1:10)

top10_brook <- hcv_brook %>%
  arrange(desc(hcv_count)) %>%
  slice(1:10)

top10_queen <- hcv_queen %>%
  arrange(desc(hcv_count)) %>%
  slice(1:10)

top10_stat <- hcv_stat %>%
  arrange(desc(hcv_count)) %>%
  slice(1:10)
```
#### Now let's look at each data frame
```{r}
top10_man
top10_bronx
top10_brook
top10_queen
top10_stat
```
### Let's pull reviews from some places in Brooklyn
```{r}
top10_brook
```
```{r}
library(googleway)

# master wok, arch diner are closed (top 1 and 2)
# let's run this on the other 8 though
# First let's just pull out the dba and latitude and longitude into single dataframe & remove first two rows
top10_brook_loc <- tail(top10_brook[c('dba', 'latitude', 'longitude')], 8)
```
```{r}
key <- 'insert key'

get_reviews <- function(df, key){
  latitude <- as.numeric(df$latitude)
  longitude <- as.numeric(df$longitude)
  
  results <- google_places(search_string = df$dba, 
                           location = c(latitude, longitude),
                           key = key) # search up location and grab information it
  
  details <- google_place_details(place_id = results$results[1, "place_id"],
                                   key = key) # grab more details based on the place_id generated prior
  
  reviews <- data.frame(details$result$reviews) # pull out 5 reviews per location
  
  if(nrow(reviews) != 0){ 
    reviews$restaurant <- df$dba # add in restaurant name if reviews are present
    reviews$rating <- details$result$rating # Add column for main average rating of the restaurant (not ratings provided by the reviewers)
  }
  
  return(reviews)
}

brook_revs <- bind_rows(apply(top10_brook_loc, 1, function(row){ # run function on data frame of top 10(ish)
  row <- as.list(row) # run it on the rows individually (we need to convert this to list to work)
  reviews <- get_reviews(row, key) # run function with personal key
  
  return(reviews)
}))

write.csv(brook_revs,"~/Desktop/Data_Viz/brook_revs.csv", row.names = FALSE)

# Unable to get reviews for Grace Caribbean Cuisine -> total of 35 reviews & ratings
```

### Let's create maps for the top 500 restaurants with the most violations across boroughs and all of NYC
```{r}
# First we need to create an 'address' object for all for labelling in the maps
hcv_man$address <- paste(hcv_man$building, hcv_man$street, hcv_man$zipcode)

hcv_total$address <- paste(hcv_total$building, hcv_total$street, hcv_total$zipcode)

hcv_brook$address <- paste(hcv_brook$building, hcv_brook$street, hcv_brook$zipcode)

hcv_stat$address <- paste(hcv_stat$building, hcv_stat$street, hcv_stat$zipcode)

hcv_queen$address <- paste(hcv_queen$building, hcv_queen$street, hcv_queen$zipcode)

hcv_bronx$address <- paste(hcv_bronx$building, hcv_bronx$street, hcv_bronx$zipcode)
```
```{r}
# To avoid crashing, let's limit it to 500 restaurants, so we'll create new dataframes similar to before
top500_man <- hcv_man %>%
  arrange(desc(hcv_count)) %>%
  slice(1:500)

top500_bronx <- hcv_bronx %>%
  arrange(desc(hcv_count)) %>%
  slice(1:500)

top500_brook <- hcv_brook %>%
  arrange(desc(hcv_count)) %>%
  slice(1:500)

top500_queen <- hcv_queen %>%
  arrange(desc(hcv_count)) %>%
  slice(1:500)

top500_stat <- hcv_stat %>%
  arrange(desc(hcv_count)) %>%
  slice(1:500)

top500_total <- hcv_total %>%
  arrange(desc(hcv_count)) %>%
  slice(1:500)
```
```{r}
library(leaflet)
library(htmltools)
# entire NYC

# by borough
# Manhattan
m <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

m1 <- m %>% addAwesomeMarkers(
  data = top500_man,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Total Violation Count:</b> ", hcv_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(top500_man$hcv_count > 0 & top500_man$hcv_count <= 20, "beige", 
                          ifelse(
                            top500_man$hcv_count >= 21 & top500_man$hcv_count <= 40, "orange",
                            ifelse(
                              top500_man$hcv_count >= 41 & top500_man$hcv_count <= 60, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-20','21-40', '41-60', '61+'),
   title = "Total Number of Violations"
)
  
m1
```
```{r}
# Bronx
m2 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

m3 <- m2 %>% addAwesomeMarkers(
  data = top500_bronx,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
 popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Total Violation Count:</b> ", hcv_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(top500_bronx$hcv_count > 0 & top500_bronx$hcv_count <= 20, "beige", 
                          ifelse(
                            top500_bronx$hcv_count >= 21 & top500_bronx$hcv_count <= 40, "orange",
                            ifelse(
                              top500_bronx$hcv_count >= 41 & top500_bronx$hcv_count <= 60, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-20','21-40', '41-60', '61+'),
   title = "Total Number of Violations"
)
  
m3
```
```{r}
# Brooklyn
m4 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

m5 <- m4 %>% addAwesomeMarkers(
  data = top500_brook,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Total Violation Count:</b> ", hcv_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(top500_brook$hcv_count > 0 & top500_brook$hcv_count <= 20, "beige", 
                          ifelse(
                            top500_brook$hcv_count >= 21 & top500_brook$hcv_count <= 40, "orange",
                            ifelse(
                              top500_brook$hcv_count >= 41 & top500_brook$hcv_count <= 60, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-20','21-40', '41-60', '61+'),
   title = "Total Number of Violations"
)
  
m5
```
```{r}
# Queens
m6 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

m7 <- m6 %>% addAwesomeMarkers(
  data = top500_queen,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Total Violation Count:</b> ", hcv_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(top500_queen$hcv_count > 0 & top500_queen$hcv_count <= 20, "beige", 
                          ifelse(
                            top500_queen$hcv_count >= 21 & top500_queen$hcv_count <= 40, "orange",
                            ifelse(
                              top500_queen$hcv_count >= 41 & top500_queen$hcv_count <= 60, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-20','21-40', '41-60', '61+'),
   title = "Total Number of Violations"
)
  
m7
```
```{r}
# Staten Island
m8 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

m9 <- m8 %>% addAwesomeMarkers(
  data = top500_stat,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Total Violation Count:</b> ", hcv_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(top500_stat$hcv_count > 0 & top500_stat$hcv_count <= 20, "beige", 
                          ifelse(
                            top500_stat$hcv_count >= 21 & top500_stat$hcv_count <= 40, "orange",
                            ifelse(
                              top500_stat$hcv_count >= 41 & top500_stat$hcv_count <= 60, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-20','21-40', '41-60', '61+'),
   title = "Total Number of Violations"
)
  
m9
```
```{r}
# Entire NYC
m10 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

m11 <- m10 %>% addAwesomeMarkers(
  data = top500_total,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Total Violation Count:</b> ", hcv_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(top500_total$hcv_count > 0 & top500_total$hcv_count <= 20, "beige", 
                          ifelse(
                            top500_total$hcv_count >= 21 & top500_total$hcv_count <= 40, "orange",
                            ifelse(
                              top500_total$hcv_count >= 41 & top500_total$hcv_count <= 60, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-20','21-40', '41-60', '61+'),
   title = "Total Number of Violations"
)
  
m11
```
### Let's create maps for the top 10 most common critical violations
```{r}
# First we need to identify which are the top 4 most common violations overall, so we'll create a brand new function
count_whole2 <- function(data){
  data %>%
    filter(inspection.date != 1900-01-01) %>%
    filter(critical.flag != 'Not Applicable') %>%
    count(violation.description, critical.flag, name = 'viol_count')
}

# Apply function & pull top 4
violations <- count_whole2(hcv) %>%
  filter(critical.flag == 'Critical') %>%
  arrange(desc(viol_count)) %>%
  slice(1:10)

violations_list <- violations$violation.description

# Let's create lists for restaurants that have these violations
viol1 <- hcv %>%
  filter(violation.description == violations_list[1])

viol2 <- hcv %>%
  filter(violation.description == violations_list[2])

viol3 <- hcv %>%
  filter(violation.description == violations_list[3])

viol4 <- hcv %>%
  filter(violation.description == violations_list[4])

viol5 <- hcv %>%
  filter(violation.description == violations_list[5])

viol6 <- hcv %>%
  filter(violation.description == violations_list[6])

viol7 <- hcv %>%
  filter(violation.description == violations_list[7])

viol8 <- hcv %>%
  filter(violation.description == violations_list[8])

viol9 <- hcv %>%
  filter(violation.description == violations_list[9])

viol10 <- hcv %>%
  filter(violation.description == violations_list[10])

#apply to whole data set such that each line is a restaurant (rather than multiple entries)
count_whole3 <- function(data){
  data %>%
    count(dba, building, street, zipcode, cuisine.description, latitude, longitude, violation.description, name = 'v_count')
}

# All of NYC
# Just to ensure that these only include ones that have had these issues before
viol1_total <- count_whole3(viol1) %>%
  filter(v_count >= 1)
viol2_total <- count_whole3(viol2)%>%
  filter(v_count >= 1)
viol3_total <- count_whole3(viol3)%>%
  filter(v_count >= 1)
viol4_total <- count_whole3(viol4)%>%
  filter(v_count >= 1)
viol5_total <- count_whole3(viol5)%>%
  filter(v_count >= 1)
viol6_total <- count_whole3(viol6)%>%
  filter(v_count >= 1)
viol7_total <- count_whole3(viol7)%>%
  filter(v_count >= 1)
viol8_total <- count_whole3(viol8)%>%
  filter(v_count >= 1)
viol9_total <- count_whole3(viol9)%>%
  filter(v_count >= 1)
viol10_total <- count_whole3(viol10)%>%
  filter(v_count >= 1)

# Now let's add in addresses
viol1_total$address <- paste(viol1_total$building, viol1_total$street, viol1_total$zipcode)
viol2_total$address <- paste(viol2_total$building, viol2_total$street, viol2_total$zipcode)
viol3_total$address <- paste(viol3_total$building, viol3_total$street, viol3_total$zipcode)
viol4_total$address <- paste(viol4_total$building, viol4_total$street, viol4_total$zipcode)
viol5_total$address <- paste(viol5_total$building, viol5_total$street, viol5_total$zipcode)
viol6_total$address <- paste(viol6_total$building, viol6_total$street, viol6_total$zipcode)
viol7_total$address <- paste(viol7_total$building, viol7_total$street, viol7_total$zipcode)
viol8_total$address <- paste(viol8_total$building, viol8_total$street, viol8_total$zipcode)
viol9_total$address <- paste(viol9_total$building, viol9_total$street, viol9_total$zipcode)
viol10_total$address <- paste(viol10_total$building, viol10_total$street, viol10_total$zipcode)
```
#### Now we can graph these individually
```{r}
v <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

v1 <- v %>% addAwesomeMarkers(
  data = viol1_total,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Violation:</b> ", violation.description, "<br>",
    "<b>Total Violation Count:</b> ", v_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(viol1_total$v_count >= 1 & viol1_total$v_count <= 2, "beige", 
                          ifelse(
                            viol1_total$v_count >= 3 & viol1_total$v_count <= 4, "orange",
                            ifelse(
                              viol1_total$v_count >= 5 & viol1_total$v_count <= 6, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-2','3-4', '5-6', '7+'),
   title = "Total Number of Violations"
)
  
v1
```
```{r}
v2 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

v3 <- v2 %>% addAwesomeMarkers(
  data = viol2_total,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Violation:</b> ", violation.description, "<br>",
    "<b>Total Violation Count:</b> ", v_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(viol2_total$v_count >= 1 & viol2_total$v_count <= 2, "beige", 
                          ifelse(
                            viol2_total$v_count >= 3 & viol2_total$v_count <= 4, "orange",
                            ifelse(
                              viol2_total$v_count >= 5 & viol2_total$v_count <= 6, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-2','3-4', '5-6', '7+'),
   title = "Total Number of Violations"
)
  
v3
```
```{r}
v4 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

v5 <- v4 %>% addAwesomeMarkers(
  data = viol3_total,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Violation:</b> ", violation.description, "<br>",
    "<b>Total Violation Count:</b> ", v_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(viol3_total$v_count >= 1 & viol3_total$v_count <= 2, "beige", 
                          ifelse(
                            viol3_total$v_count >= 3 & viol3_total$v_count <= 4, "orange",
                            ifelse(
                              viol3_total$v_count >= 5 & viol3_total$v_count <= 6, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-2','3-4', '5-6', '7+'),
   title = "Total Number of Violations"
)
  
v5
```
```{r}
v6 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

v7 <- v6 %>% addAwesomeMarkers(
  data = viol4_total,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Violation:</b> ", violation.description, "<br>",
    "<b>Total Violation Count:</b> ", v_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(viol4_total$v_count >= 1 & viol4_total$v_count <= 2, "beige", 
                          ifelse(
                            viol4_total$v_count >= 3 & viol4_total$v_count <= 4, "orange",
                            ifelse(
                              viol4_total$v_count >= 5 & viol4_total$v_count <= 6, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-2','3-4', '5-6', '7+'),
   title = "Total Number of Violations"
)
  
v7
```
```{r}
v8 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

v9 <- v8 %>% addAwesomeMarkers(
  data = viol5_total,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Violation:</b> ", violation.description, "<br>",
    "<b>Total Violation Count:</b> ", v_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(viol5_total$v_count >= 1 & viol5_total$v_count <= 2, "beige", 
                          ifelse(
                            viol5_total$v_count >= 3 & viol5_total$v_count <= 4, "orange",
                            ifelse(
                              viol5_total$v_count >= 5 & viol5_total$v_count <= 6, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-2','3-4', '5-6', '7+'),
   title = "Total Number of Violations"
)
  
v9
```
```{r}
v10 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

v11 <- v10 %>% addAwesomeMarkers(
  data = viol6_total,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Violation:</b> ", violation.description, "<br>",
    "<b>Total Violation Count:</b> ", v_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(viol6_total$v_count >= 1 & viol6_total$v_count <= 2, "beige", 
                          ifelse(
                            viol6_total$v_count >= 3 & viol6_total$v_count <= 4, "orange",
                            ifelse(
                              viol6_total$v_count >= 5 & viol6_total$v_count <= 6, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-2','3-4', '5-6', '7+'),
   title = "Total Number of Violations"
)
  
v11
```
```{r}
v12 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

v13 <- v12 %>% addAwesomeMarkers(
  data = viol7_total,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Violation:</b> ", violation.description, "<br>",
    "<b>Total Violation Count:</b> ", v_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(viol7_total$v_count >= 1 & viol7_total$v_count <= 2, "beige", 
                          ifelse(
                            viol7_total$v_count >= 3 & viol7_total$v_count <= 4, "orange",
                            ifelse(
                              viol7_total$v_count >= 5 & viol7_total$v_count <= 6, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-2','3-4', '5-6', '7+'),
   title = "Total Number of Violations"
)
  
v13
```
```{r}
v14 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

v15 <- v14 %>% addAwesomeMarkers(
  data = viol8_total,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Violation:</b> ", violation.description, "<br>",
    "<b>Total Violation Count:</b> ", v_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(viol8_total$v_count >= 1 & viol8_total$v_count <= 2, "beige", 
                          ifelse(
                            viol8_total$v_count >= 3 & viol8_total$v_count <= 4, "orange",
                            ifelse(
                              viol8_total$v_count >= 5 & viol8_total$v_count <= 6, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-2','3-4', '5-6', '7+'),
   title = "Total Number of Violations"
)
  
v15
```
```{r}
v16 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

v17 <- v16 %>% addAwesomeMarkers(
  data = viol9_total,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Violation:</b> ", violation.description, "<br>",
    "<b>Total Violation Count:</b> ", v_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(viol9_total$v_count >= 1 & viol9_total$v_count <= 2, "beige", 
                          ifelse(
                            viol9_total$v_count >= 3 & viol9_total$v_count <= 4, "orange",
                            ifelse(
                              viol9_total$v_count >= 5 & viol9_total$v_count <= 6, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-2','3-4', '5-6', '7+'),
   title = "Total Number of Violations"
)
  
v17
```
```{r}
v18 <- leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(lng = -74.0060, lat = 40.7128, zoom = 12)

v19 <- v18 %>% addAwesomeMarkers(
  data = viol10_total,
  lng = ~longitude, 
  lat = ~latitude,
  clusterOptions = markerClusterOptions(),
  popup = ~paste(
    "<h4>", dba, "</h4>",
    "<b>Address:</b> ", address, "<br>",
    "<b>Cusisine Type:</b> ", cuisine.description, "<br>",
    "<b>Violation:</b> ", violation.description, "<br>",
    "<b>Total Violation Count:</b> ", v_count, "<br>"
  ),
  label = ~dba,
  icon = awesomeIcons(
    icon = 'info-circle',  # Valid FontAwesome icon
    markerColor = ifelse(viol10_total$v_count >= 1 & viol10_total$v_count <= 2, "beige", 
                          ifelse(
                            viol10_total$v_count >= 3 & viol10_total$v_count <= 4, "orange",
                            ifelse(
                              viol10_total$v_count >= 5 & viol10_total$v_count <= 6, "red",
                          "darkred"))),
    library = 'fa'  # Use FontAwesome instead of glyphicon
  )
) %>% addLegend( 
   'bottomright' , 
   colors=c("beige","orange", "red", "darkred"),
   labels=c('1-2','3-4', '5-6', '7+'),
   title = "Total Number of Violations"
)
  
v19
```





